### ISSUE TITLE
Setup a test server

### ISSUE THREAD

**Issue by fengelniederhammer** [GenSpectrum/LAPIS#124]
Setup a test server where both SILO and LAPIS v2 are running so that we can test the integration not only locally.

**Comment by fengelniederhammer** [comment]
We postpone this to a later point. For small datasets, we can run tests in Github actions. For larger datasets, we need some preparation.

**Comment by fengelniederhammer** [comment]
Some details that we discussed:
* On the server, we need Docker and nginx.
* We use nginx as a simple proxy to forward to the running Docker containers.
* We try to use Ansible to setup Docker and nginx so that we can reuse it on a production server ( @chaoran-chen where should we put the Ansible code? Also into the LAPIS repo?)

**Comment by fengelniederhammer** [comment]
- [ ] #252 
- [ ] #253 
- [ ] https://github.com/GenSpectrum/LAPIS-SILO/issues/108

**Comment by chaoran-chen** [comment]
Let's put the Ansible code (and nginx configs, etc.) first in a private repository. Later, we can publish the general/reusable parts.

Just create a repo: https://github.com/GenSpectrum/servers
