### ISSUE TITLE
Advanced Queries

### ISSUE THREAD

**Issue by fengelniederhammer** [GenSpectrum/LAPIS#130]
Implement advanced queries for mutations such as `(B.1.1.529* | S:67V) & !C913T`. This requires parsing (probably using Antlr) and translating them into a SILO query. The concept of advanced query only exists in LAPIS. SILO only knows SILO queries.

Open points:
* Do we allow filtering for sequence metadata in advanced queries?
* How exactly does the generalized version of mutation queries look like? Problem: Pathogens might have more that one genetic sequence, i.e. A501T is ambiguous in that case.

Details:
tbd

**Comment by JonasKellerer** [comment]
We should also include here, that the variantQueries for SarsCov2 do not allow to specify the column in Silo. Currently they are hard coded. In a general approach, this should no longer be the case.

**Comment by chaoran-chen** [comment]
We have already advanced queries for SARS-CoV-2. If we want to generalize, we can create a new ticket.
