### ISSUE TITLE
Implement a request cache

### ISSUE THREAD

**Issue by fengelniederhammer** [GenSpectrum/LAPIS#137]
Cache requests to reduce load on SILO.

Details:
- the cache should be invoked for:
    - /nucleotideMutations
    - /aminoAcidMutations
    - /nucleotideInsertions
    - /aminoAcidInsertions
- other routes should be ignored
- when a new data version is available the cache should be invalidated

**Comment by JonasKellerer** [comment]
Do we still plan on doing this? It seems, that SILO can handle large number of requests. Or do we keep this open, until we see the results from the production server?

**Comment by chaoran-chen** [comment]
Yes, let's keep it for a while and then analyze the response times.

**Comment by JonasKellerer** [comment]
As discussed, we will now introduce a request cache, similar to v1.

This is necessary, due to large load on SILO (mainly on the collections page.) See https://github.com/GenSpectrum/LAPIS-SILO/issues/298

**Comment by JonasKellerer** [comment]
I updated the description.
