### ISSUE TITLE
Conventional commits linter

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/LAPIS#169]
To have even more linters, we could run [commitlint](https://github.com/conventional-changelog/commitlint) in the CI to ensure that the commit messages follow the conventional commit standard.

This does not only apply to this repository but to all of our repositories.

**Comment by chaoran-chen** [comment]
@fengelniederhammer, @JonasKellerer, what do you think? Would this be useful for all our repos?

**Comment by fengelniederhammer** [comment]
Certainly - especially since we have more people working on the code now.
