### ISSUE TITLE
LAPIS seems to be down

### ISSUE THREAD

**Issue by jpflorido** [GenSpectrum/LAPIS#172]
Hi there,
It seems LAPIS is not working:
https://lapis.cov-spectrum.org/open/v1/sample/aggregated?pangoLineage=B.1.617.2
Thanks,
Javier

**Comment by chaoran-chen** [comment]
Thank you very much, @jpflorido, for reporting it! I didn't notice. It is up again.

**Comment by jpflorido** [comment]
Hi,
Thanks for your reply!! But it seems not working yet: https://lapis.cov-spectrum.org/open/v1/sample/aggregated?pangoLineage=B.1.617.2

Thanks!

**Comment by chaoran-chen** [comment]
@jpflorido Oh, that's strange. For me, it is working:

![image](https://user-images.githubusercontent.com/18666552/224947053-9f0152ef-bfb6-4cf9-bce1-14872e4663e5.png)

What are you seeing?

**Comment by jpflorido** [comment]
Sorry, it works!!! 
Thanks,
Javier
