### ISSUE TITLE
Implement `/aa-mutations` returning JSON

### ISSUE THREAD

**Issue by fengelniederhammer** [GenSpectrum/LAPIS#288]
Call SILO with the "AminoAcidMutations" action.

**Comment by chaoran-chen** [comment]
I think that the notation works quite well, so I'd like to keep the behavior for LAPIS.

**Comment by fengelniederhammer** [comment]
How do we handle this in SILO then? Do we keep the current behavior and add a logic like "if the sequence name is not set, then return the results for all sequences"?

Should we maybe let SILO return data in this form?
```
    {
      "count": 4,
      "sequenceName": "S"
      "position": "L18F",
      "proportion": 0.041237113402061855
    },
```
This is probably more convenient for users, since you don't have to split it apart. In LAPIS, we could do the mapping to "S:L18F".

I think we also need to spend some thoughts on `/nucleotideMutations`, since the same applies there, too (now that we support  multiple nucleotide sequences).

**Comment by fengelniederhammer** [comment]
Also do you have a strong opinion on the default `minProportion`? The old LAPIS uses 0.05, SILO uses 0.02. If we could use the same for both, then we could get rid of some logic in the new LAPIS.

**Comment by chaoran-chen** [comment]
I don't have a strong opinion but if there is no good reason for deviating from 0.05, I'd suggest keeping it just for backward compatibility.

**Comment by fengelniederhammer** [comment]
Then I'd suggest to change it in SILO.

**Comment by fengelniederhammer** [comment]
This requires https://github.com/GenSpectrum/LAPIS-SILO/issues/191
-> Postpone this until it's finished.

**Comment by JonasKellerer** [comment]
As discussed the API should look like this:
1. Request to LAPIS (POST /aminoAcidMutations)
`
{
	filters: List
	minProportion: 0.05
}
`
It should not be filterable after sequenceName/gene

2. Request to SILO /query
`
{
    "action": {
      "type": "AminoAcidMutations",
      "minProportion": 0.05
    },
    "filterExpression": {
        ... list of filters
    }
`
`sequenceName` is left empty
3. Response from SILO
`
{
      "count": 37,
      "mutation": "T19R",
      "proportion": 0.015,
      "sequenceName": "S"
}
`
4. Response from LAPIS
`
[
{mutation: "S:T19R", count: 123, proportion: 0.123}
]
`


1. Request to LAPIS (POST /nucleotideMutations)
`
{
	filters: List
	minProportion: 0.05
}
`
It should not be filterable after sequenceName/gene

2. Request to SILO /query
`
{
    "action": {
      "type": "Mutations",
      "minProportion": 0.05
    },
    "filterExpression": {
        ... list of filters
    }
`
`sequenceName` is left empty

3. Response from SILO
`
[
{
      "count": 37,
      "mutation": "A19T",
      "proportion": 0.015,
      "sequenceName": "main"
},
{
      "count": 123,
      "position": "A123T",
      "mutation": 0.015,
      "sequenceName": "someOtherSequence"
}
]
`
4. Response from LAPIS
`
[
{mutation: "A19T", count: 123, proportion: 0.123}
{mutation: "someOtherSequence:A123T", count: 123, proprotion: 0.015}
]
`
If the returned sequence name is "main" then LAPIS should return only the mutation. If it has some other same, then  it should be included in the mutations field (shown above).
