### ISSUE TITLE
Hand `orderByFields`, `limit` and `offset` to SILO

### ISSUE THREAD

**Issue by fengelniederhammer** [GenSpectrum/LAPIS#290]
SILO allows the fields `orderByFields`, `limit` and `offset` on every action. Accept them as additional query parameters (GET requests) or in the response body (POST requests) and pass them on.

**Comment by chaoran-chen** [comment]
It would actually be great if you can support ascending/descending as well but I'm not sure what a good and easy format would be.

Would `...?orderBy=country(asc),date(desc)` be a good syntax (where the order is optional)? `(` and `)` do not need special encoding, so it is possible to type such an URL easily by hand.

Happy to hear other suggestions!

**Comment by fengelniederhammer** [comment]
At least in POST requests we could accept both (similar to SILO)
```
{ "orderBy": ["country", "date"] }
```
and
```
{ "orderBy": [
   { "field": "country", "type": "descending" },
   { "field": "date", "type": "ascending" }
]}
```
We could also decide to only allow the second version, since we expect POST requests to be mostly generated programmatically, so we don't need a short version.

Do we need to support this in GET requests? I don't have any better idea and I suspect that no one might ever use that.

**Comment by chaoran-chen** [comment]
Good point, only supporting that in POST requests would be enough probably! Let's do that for now.
