### ISSUE TITLE
Implement `/nuc-sequence`

### ISSUE THREAD

**Issue by JonasKellerer** [GenSpectrum/LAPIS#314]
Similar to LAPIS v1

`/fasta` should also map to this endpoint

**Comment by chaoran-chen** [comment]
See https://github.com/GenSpectrum/LAPIS/issues/313#issuecomment-1662062290

**Comment by JonasKellerer** [comment]
This ticket is waiting on https://github.com/GenSpectrum/LAPIS-SILO/issues/131
