### ISSUE TITLE
Filter by insertions

### ISSUE THREAD

**Issue by fengelniederhammer** [GenSpectrum/LAPIS#318]
https://github.com/GenSpectrum/LAPIS-SILO/pull/166 made it possible to filter sequences by insertions. Expose this via LAPIS.

How do we implement this in LAPIS 2? The old LAPIS offers two fields `nucInsertions` and `aaInsertions`, but SILO has columns of type `insertion` that need to be configured.

**Comment by Taepper** [comment]
I see that this introduces the problem that the grammar will no longer differentiate between `nuc_ins` and `aa_ins`:
`ins: 'INS_' name ':' position ':' (mutated | '?')+;`
which might be undesirable.
Alternatively we might want to have different prefixes for these filters

**Comment by JonasKellerer** [comment]
For discussion:
Idea:
- specify two fields like for mutations and name them "nucleotideInsertions" and "aminoAcidInsertions"
- provide these fields with a list of insertions of the form "position:Symbols" / "gene:position:Symbols"
Problem:
- multiple nucleotide sequences can have insertions. Does SILO store them like aminoAcids or does lapis do the mapping to the specific columns?
- Do we make the metadata column insertion in SILO configurable, or not?

**Comment by Taepper** [comment]
In SILO there are the column types "insertion" and "aaInsertion" as requested, as there can be overlap between gene names and segment names

**Comment by JonasKellerer** [comment]
As discussed:
- SILO will use/return all columns of insertions, when the column is not provided in the query (both for filter and action)
