### ISSUE TITLE
How to get a csv with all countries sequencing intensities country by country??

### ISSUE THREAD

**Issue by FedeGueli** [GenSpectrum/LAPIS#336]
Hi @chaoran-chen there is a way to get sequencing intensity of each country from CovSpectrum??

**Comment by chaoran-chen** [comment]
@FedeGueli Here is a list with the number of sequences per country and day since 1 June on GISAID. Is that what you are looking for?

[sequences_per_country_and_date.csv](https://github.com/GenSpectrum/LAPIS/files/12376784/sequences_per_country_and_date.csv)

**Comment by FedeGueli** [comment]
Thank you very much Chaoran!
