### ISSUE TITLE
Develop preprocessing pipeline

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/LAPIS#372]
For 

- [x] SC2 open - it's almost finished but a few minor adjustments are needed
- [x] GISAID

**Comment by JonasKellerer** [comment]
- The pipeline downloads the data from the servers
- The output is a ndjson file with the data

**Comment by chaoran-chen** [comment]
Bug detected by @Taepper: there is one sequence in the open dataset where `strain` is null. I need to fix it..

**Comment by corneliusroemer** [comment]
Sorry this is a stupid bug on our end, we should just exclude that line from the metadata in ncov ingest. But yeah, this won't happen quickly

**Comment by fengelniederhammer** [comment]
We have ingest pipelines for both datasets.
