### ISSUE TITLE
Set up one preprocessing instance on test server

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/LAPIS#373]
- It should be automatically started regularly with a cron job.
- It should use SC2 Nextstrain open data

**Comment by JonasKellerer** [comment]
For the full data we need more RAM for both preprocessing and serving silo than we have. Thus, we perform the preprocessing currently by hand (stopping the running silo container).

**Comment by JonasKellerer** [comment]
We moved the preprocessing to the production server. Do we still need this ticket? Or do we want to change it, so we do the preprocessing on the testserver with a smaller sample size?

**Comment by chaoran-chen** [comment]
Let's close it and we can think about setting up a test preprocessing pipeline later.
