### ISSUE TITLE
Validate LAPIS v2's results

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/LAPIS#374]
We should check LAPIS v2 against v1.

**Comment by fengelniederhammer** [comment]
I assume that we manually test the previously deployed V2 instance on our test server against the productive open V1 instance (https://lapis.cov-spectrum.org/open/v1/)?

**Comment by chaoran-chen** [comment]
yes!

**Comment by JonasKellerer** [comment]
We have already LAPISv2 running for production. I will move this to the backlog. We can remove this once we have fully switched to LAPISv2.

**Comment by chaoran-chen** [comment]
Done by now :)
