### ISSUE TITLE
DOC: Is dateTo inclusive or exclusive

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/LAPIS#49]
Was just wondering whether dateTo is inclusive or exclusive.

https://cov-spectrum.ethz.ch/public/#response-format

Couldn't find it written in the docs. Thanks!

**Comment by chaoran-chen** [comment]
It's inclusive.

**Comment by fengelniederhammer** [comment]
This is documented for LAPIS 2 now, so I'm closing this.
https://github.com/GenSpectrum/LAPIS/blob/e0439f924f302bee9e559a2b91a28c4a3972f793/lapis2-docs/src/components/FiltersTable/getFilters.tsx#L14-L27
