### ISSUE TITLE
Docs: Rework "Response format"

### ISSUE THREAD

**Issue by fengelniederhammer** [GenSpectrum/LAPIS#563]
Do we need it at all? Should be redundant with the Swagger UI.

If we keep it, fix it. It's probably not up to date with LAPIS 2.

**Comment by chaoran-chen** [comment]
I think that the Swagger UI is only really useful for people who have some decent experience with web APIs but we also have to target users who might have never used any other web APIs before, so we need documentation that is easier (more welcoming/less intimidating) to read.
