### ISSUE TITLE
Error shown in Covspectrum when searching S:T572I, S:R346T 

### ISSUE THREAD

**Issue by FedeGueli** [GenSpectrum/LAPIS#584]
Both in collections lineages carrying S:t572I and in the plain query i have troubles to display S:T572I, S:R346T.

Re checking i think all Spike mutations are not working right now @chaoran-chen

**Comment by FedeGueli** [comment]
Sorry all single AA mutation queries fail to be displayed: 
<img width="869" alt="Screenshot 2024-01-22 alle 11 12 36" src="https://github.com/GenSpectrum/LAPIS/assets/87669813/5770599b-1494-4114-abeb-582c9fad11b5">

**Comment by krosa1910** [comment]
Update: (On my side)
Spike is dead, both S:L452R and T22917G are not working, but I think non-Spike is only dead for AA mutations, nuc is still doable (I tried some random ones like 12345A, not trying everything in a good manner.)

**Comment by FedeGueli** [comment]
yes it seemed that way to me too even if then i was looking for G17562T  and it gave me an error too
<img width="681" alt="Screenshot 2024-01-22 alle 11 18 47" src="https://github.com/GenSpectrum/LAPIS/assets/87669813/7c62c3e3-5cfa-4c1f-87c1-75bbcc84a415">

**Comment by krosa1910** [comment]
> yes it seemed that way to me too even if then i was looking for G17562T and it gave me an error too <img alt="Screenshot 2024-01-22 alle 11 18 47" width="681" src="https://private-user-images.githubusercontent.com/87669813/298543934-7c62c3e3-5cfa-4c1f-87c1-75bbcc84a415.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTkwNjcsIm5iZiI6MTcwNTkxODc2NywicGF0aCI6Ii84NzY2OTgxMy8yOTg1NDM5MzQtN2M2MmMzZTMtNWNmYS00YzFmLTg3YzEtNzViYmNjODRhNDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDEwMTkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MTY1MDk4NDJiNjQ0ODBkZmNlNzUyMWUxZjZiYjNhY2Q1MmFkNjFjNWFhMTA5NzBjNGU1YWVmM2U4Njg4YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A4E0s6mq_nA3zjPGgjrbKk4Lerg2_CuqQgJKFpedayk">

I manually tried some intervals, it seems that 16201-21177 for nuc is dead, and very likely everything for aa is dead. not sure everything else is good

**Comment by krosa1910** [comment]
> > yes it seemed that way to me too even if then i was looking for G17562T and it gave me an error too <img alt="Screenshot 2024-01-22 alle 11 18 47" width="681" src="https://private-user-images.githubusercontent.com/87669813/298543934-7c62c3e3-5cfa-4c1f-87c1-75bbcc84a415.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTkwNjcsIm5iZiI6MTcwNTkxODc2NywicGF0aCI6Ii84NzY2OTgxMy8yOTg1NDM5MzQtN2M2MmMzZTMtNWNmYS00YzFmLTg3YzEtNzViYmNjODRhNDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDEwMTkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MTY1MDk4NDJiNjQ0ODBkZmNlNzUyMWUxZjZiYjNhY2Q1MmFkNjFjNWFhMTA5NzBjNGU1YWVmM2U4Njg4YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A4E0s6mq_nA3zjPGgjrbKk4Lerg2_CuqQgJKFpedayk">
> 
> I manually tried some intervals, it seems that 16201-21177 for nuc is dead, and very likely everything for aa is dead. not sure everything else is good

Some other random islands, like 21178-23060 seems good but 23061-24xxx seems bad

**Comment by ujoshi4** [comment]
Error Shown when searching Jn.1.11, S:456L

![image](https://github.com/GenSpectrum/LAPIS/assets/123217264/eb5543f5-8eef-40e0-89b9-6201b82cb109)

**Comment by ujoshi4** [comment]
Error shown when searching JN.1.11 S:F456L
![image](https://github.com/GenSpectrum/LAPIS/assets/123217264/63c3a7a4-5bf9-4260-8ecf-35678cb1e939)

**Comment by FedeGueli** [comment]
Thx @chaoran-chen sorry for not closing it !
