### ISSUE TITLE
Major/ COVSPECTRUM: Number of sequences is not shown after the new update in the Nextclade mode

### ISSUE THREAD

**Issue by FedeGueli** [GenSpectrum/LAPIS#601]
It seems something messed up with the last upload. 
When selecting for Nextclade pango lineage zeros equences are shown. 
Instead while searching for nextstrain clades or pango something shows up but with weird results. JN.1 scores infinity for example:

<img width="1206" alt="Screenshot 2024-01-29 alle 11 16 04" src="https://github.com/GenSpectrum/LAPIS/assets/87669813/5399f1a8-60f1-4d82-8782-2c07adfa7e52">
<img width="1111" alt="Screenshot 2024-01-29 alle 11 16 41" src="https://github.com/GenSpectrum/LAPIS/assets/87669813/e9721524-1ee9-4679-a595-0bbecfdf6534">
<img width="1053" alt="Screenshot 2024-01-29 alle 11 16 55" src="https://github.com/GenSpectrum/LAPIS/assets/87669813/f1dae82a-4aa5-4c57-9641-8b561c643188">
<img width="1140" alt="Screenshot 2024-01-29 alle 11 17 19" src="https://github.com/GenSpectrum/LAPIS/assets/87669813/271f25ea-dc37-4235-9e44-0fb29e5b1f17">

**Comment by chaoran-chen** [comment]
Sorry for the interruption! I have to restart the server again to fix the error.
