### ISSUE TITLE
Advanced queries not cached?

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/LAPIS#65]
I've noticed that when I request GISAID EPI_ISLs of advanced queries then the load takes about the same dozen of seconds as it takes when I request it on the normal website.

Could it be that advanced queries are not cached?

**Comment by chaoran-chen** [comment]
We only cache aggregated data. Lists of sample IDs are not cached.

**Comment by corneliusroemer** [comment]
Interesting, I would have thought that you cache queries and not (just) the aggregation as the queries are what may take the longest? At least when the queries are complicated :)

**Comment by chaoran-chen** [comment]
Everything will be better with the new engine ;)
