### ISSUE TITLE
Mutations often don't load

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/LAPIS#666]
@ryhisner noticed that the mutations don't load on some CoV-Spectrum pages: [example](https://cov-spectrum.org/explore/World/AllSamples/from%3D2022-01-06%26to%3D2024-02-17/variants?variantQuery=%21ORF1a%3AE10*+%26+%21C28256T+%26+%21C897A+%26+%5B2-of%3A+S%3AP621%2C+S%3AV622%2C+S%3AI624%2C+S%3AH625%2C+S%3AA626%2C+S%3AD627%2C+S%3AQ628%2C+S%3AP631%2C+S%3AR634%2C+S%3AT638%2C+S%3AG639%2C+S%3AS640%2C+S%3AN641%2C+S%3AV642G%2C+S%3AF643%2C+S%3AF643-%5D&variantQuery1=nextcladePangoLineage%3AXBB.1.42*+%26+A29799T&)

I was able to confirm that:

<details>
<summary>Screenshot</summary>

![image](https://github.com/GenSpectrum/cov-spectrum-website/assets/18666552/863bf474-9d8a-485e-bc4c-8e948e21b5d2)
</details>

LAPIS is throwing a lot of 500 errors. Some request IDs:

- 37990764-3240-458a-b546-93b674a9a23c
- 6b712bd6-57f4-4528-8a62-5b02d1e6907e
- d3147aca-f26d-492f-bb65-edaf00016c85
- 1f890fac-33c9-4e32-951a-5a03dcead3d8

**Comment by fengelniederhammer** [comment]
This is very likely a load problem. We are investigating in https://github.com/GenSpectrum/LAPIS-SILO/issues/298, so I'll move this to blocked for now.
