### ISSUE TITLE
Versioned releases or docker tags

### ISSUE THREAD

**Issue by theosanderson** [GenSpectrum/LAPIS#678]
It would be cool if LAPIS had some sort of versioned releases, particularly with respect to the Docker images, so one can pin to a particular version. At minimum this could just be tagging images with commit hashes? Or it could be real versioning.

Thanks!

**Comment by fengelniederhammer** [comment]
If we want to pin versions in Loculus, I would propose to use hashes for now. We don't have a versioning concept yet, and I think we won't in the next couple weeks.

**Comment by fengelniederhammer** [comment]
Related to https://github.com/GenSpectrum/LAPIS-SILO/issues/309

**Comment by chaoran-chen** [comment]
Using commit hashes sounds good for now.

**Comment by theosanderson** [comment]
👍  As I understand it this still needs a change to the workflow to tag with the hash (but I may be wrong and there may be a workaround)

**Comment by fengelniederhammer** [comment]
I think you can also pull by specifying the digest: `ghcr.io/genspectrum/lapis-v2@sha256:d9a321837e4a956f6f3a5d240cc577884607d96d94aa657b92b40d39b9bd5607`. Not a nice version, but requires no effort. Commit hashes are shorter, but equally useless to humans.

**Comment by theosanderson** [comment]
Cool!

**Comment by theosanderson** [comment]
I wasn't able to get Fabian's solution working with kubernetes unfortunately
