### ISSUE TITLE
Usage and performance statistics

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/LAPIS#69]
It would be very useful to gather some usage and performance data. I suggest collecting the following data for each request:

- Date or date+hour+minute (or exact timestamp?)
- Endpoint
- Cache hit/miss
- Response time
- Variant

We get roughly 500,000 requests per day.

The easiest solution could be just writing the data to a log file? I'm open to ideas about the technical implementation and how we can easily get some statistics/plots!

**Comment by fengelniederhammer** [comment]
Fields to identify a variant by: See VariantSelector in React code.

**Comment by chaoran-chen** [comment]
A few more ideas regarding this issue:

- It would be good if the path where the logs are stored can be configured. By default, maybe put them in `./logs`?
- A new file should be created for each day.
- Bonus feature: older files will automatically be compressed
