### ISSUE TITLE
insertion not in orderBy fields for nucleotideInsertions and aminoAcidInsertions

### ISSUE THREAD

**Issue by mneacsu** [GenSpectrum/LAPIS#710]
When I try ordering insertions by their name like this:
[https://lapis.cov-spectrum.org/gisaid/v2/sample/aminoAcidInsertions?accessKey={accessKey}&orderBy=insertion&limit=3](https://lapis.cov-spectrum.org/gisaid/v2/sample/aminoAcidInsertions?accessKey={accessKey}&orderBy=insertion&limit=3), 
I get `"Error from SILO: OrderByField insertion is not contained in the result of this operation."`

**Comment by fengelniederhammer** [comment]
Thanks for bringing this up! The fields of this class are the fields by which you can order by:
```
data class InsertionData(
    val count: Int,
    val insertions: String,
    val position: Int,
    val sequenceName: String,
)
```

1. This is a mistake in the LAPIS Swagger UI that we should fix. It states that you can sort by `insertion` and `count`: https://github.com/GenSpectrum/LAPIS/blob/9c10560e139d65965897581e156b08ef76522ad4/lapis2/src/main/kotlin/org/genspectrum/lapis/openApi/OpenApiDocs.kt#L509
2. SILO doesn't permit to sort by the `insertion` (which is of the form `"ins_${it.sequenceName}:${it.position}:${it.insertions}"`). One can of course replicate this behavior by sorting for `sequenceName,position,insertions`. It might be confusing for users though. @Taepper @chaoran-chen What should we do about that?
3. SILO should state what allowed values are (https://github.com/GenSpectrum/LAPIS-SILO/blob/208e8b2724d97a1cc83342e068f5f53337715637/src/silo/query_engine/actions/insertions.cpp#L56)
