### ISSUE TITLE
Return mutations and insertions as structured data

### ISSUE THREAD

**Issue by JonasKellerer** [GenSpectrum/LAPIS#718]
SILO now returns structured data for insertions and mutations. This should now also be returned by LAPIS. The SILO PR on insertions https://github.com/GenSpectrum/LAPIS-SILO/pull/373 waits on this issue to be merged. The mutations PR is already merged (https://github.com/GenSpectrum/LAPIS-SILO/pull/357).

The data looks like this:
Mutations: 
```
{
      "count": 37,
      "mutation": "T19R",
      "mutationFrom": "T",
      "mutationTo": "R",
      "position": 19,
      "proportion": 0.38144329896907214,
      "sequenceName": "S"
 }
```

Insertions:
```
{
      "count": 5,
      "inserted_symbols": "EPE",
      "insertion": "ins_S:214:EPE",
      "position": 214,
      "sequenceName": "S"
    },
```

**Comment by Taepper** [comment]
`inserted_symbols` change to `insertedSymbols` for js conformity
