### ISSUE TITLE
Gisaid endpoints giving a 403 error

### ISSUE THREAD

**Issue by shoulton-invivyd** [GenSpectrum/LAPIS#719]
Hello,
When hitting the endpoints defined here: {[https://lapis.cov-spectrum.org/gisaid/v2/docs/references/open-api-definition/#_top}](https://lapis.cov-spectrum.org/gisaid/v2/docs/references/open-api-definition/#_top%7D) from the browser I am getting a 403 CORS error. Previously, I was able to hit V1 endpoints without error, but since switching to V2 endpoints in the last few weeks I now get the following error:

blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Oddly, I am able to call the V2 gisaid endpoints with Postman without error. Yet regardless of browser used (Chrome vs. Firefox, etc.) I get the 403 CORS error.

The GenBank endpoints defined here {[https://lapis.cov-spectrum.org/openapi/}](https://lapis.cov-spectrum.org/openapi/%7D) are also still working perfectly for me within the browser.

Is there something I’m missing to make the V2 endpoints work again in my code? Or is this an error with CORS permisisons on the covspectrum server since the recent update? Thank you!

Note: This is cross-posted [here](https://github.com/GenSpectrum/cov-spectrum-server/issues/39) as well because I wasn't sure which github was the proper place for this.

**Comment by chaoran-chen** [comment]
Hi @shoulton-invivyd, thank you for reaching out! You're getting a 403 error because the GISAID instance of LAPIS is internal and designed for CoV-Spectrum. It is not a public instance.
