### ISSUE TITLE
ENH: Offer zstd encoding for pareto superior compression

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/LAPIS#738]
Recently, zstd has become supported in Chromium alongside br, gzip and deflate as a supported compression method.

It might be worth looking into using it for on the fly compression for LAPIS as that's exactly the domain where zstd is absolutely amazing: fast compression on server side, good compression ratios, fast decompression in browser.

I had that idea when I noticed you use gzip for the many requests for covSpectrum:
<img width="1721" alt="image" src="https://github.com/GenSpectrum/LAPIS-SILO/assets/25161793/3041c1ca-5ddd-4edf-8c23-855c76a770be">

<img width="1588" alt="image" src="https://github.com/GenSpectrum/LAPIS-SILO/assets/25161793/1951e07a-2075-4ce8-8a67-dc0fbe90c1a1">

https://caniuse.com/mdn-http_headers_content-encoding_zstd

**Comment by fengelniederhammer** [comment]
If at all, this should be implemented in LAPIS, so I transferred the issue.

**Comment by corneliusroemer** [comment]
I did a quick test including/excluding gzip from the content-encoding accept header using requestly and these are the results (caching disabled):

Zstd:
<img width="1697" alt="image" src="https://github.com/GenSpectrum/LAPIS/assets/25161793/0d4215f3-424f-4710-a906-953f1581d6f4">

Gzip:
<img width="1495" alt="image" src="https://github.com/GenSpectrum/LAPIS/assets/25161793/a9223614-1859-451d-b1b2-abe7a99113fa">

Note that zstd is slightly less efficient in compressing, but server responses are faster. I wonder if zstd compression strength can be increased.
