### ISSUE TITLE
Wildcard based searches

### ISSUE THREAD

**Issue by theosanderson** [GenSpectrum/LAPIS#750]
It would be nice to be able to search strings using wildcards. E.g. if my sequences have a `name` column which might look like `AWESOME-LAB/SEQUENCE_22` it would be cool to be able to search with `AWESOME-LAB*` to find all awesome lab sequences.

**Comment by Taepper** [comment]
Having an SQL-equivalent LIKE statement would maybe be a sensible generalisation of this?

**Comment by theosanderson** [comment]
(yes, that would be great!)

**Comment by fengelniederhammer** [comment]
To specify this a bit further in SILO terms: What do we want to support? A `StringLike` filter? What does it accept? Regex? Just a "string contains this value" functionality?

**Comment by chaoran-chen** [comment]
Also to think about: should we support case-insensitive string search?

**Comment by corneliusroemer** [comment]
Nice thing about regex would be ability for implementor to decide whether they want things like: case-insensitive, substring, etc. It would allow LAPIS to not have to make the decision, at the expense of slightly increased complexity as it would have to include regex code.

With regex type, downstream code would be able to implement all those variations by simply changing the regex query generated.

**Comment by anna-parker** [comment]
This will be really helpful for the authors search!

**Comment by corneliusroemer** [comment]
What's the status on this?

**Comment by Taepper** [comment]
I am currently working on this issue in SILO -> [#517](https://github.com/GenSpectrum/LAPIS-SILO/issues/517)

**Comment by fengelniederhammer** [comment]
Done with #897
