### ISSUE TITLE
Filter by `null` values

### ISSUE THREAD

**Issue by fengelniederhammer** [GenSpectrum/LAPIS#757]
It should be possible to filter for `null` valued fields.

I just checked on the Loculus Ebola instance:

### For GET requests it seems to work:
`GET /sample/details?accessionVersion=LOC_0001D2F.1&ncbi_is_lab_host=` yields a result.
Taken from this swagger request:
![grafik](https://github.com/GenSpectrum/LAPIS/assets/92720311/270b7c68-7be6-4938-a2d7-96bd6b7e4fe8)

### For POST it does not

```
POST /sample/details
{
  "accessionVersion": "LOC_0001D2F.1",
  "ncbi_is_lab_host": null
}
``` 

yields no result.

```
POST /sample/details
{
  "accessionVersion": "LOC_0001D2F.1"
}
``` 
yields the same result as the GET request.

### Expected behavior

* Both GET and POST should return the same results.
* For both methods it should be possible to filter by `null`. This should be possible for every sequence filter field that LAPIS offers.

**Comment by chaoran-chen** [comment]
Are you sure that it works with GET? I wasn't aware that we ever implemented support for querying `null` and I assumed that it is currently not possible with SILO.

**Comment by fengelniederhammer** [comment]
SILO supports it:
* https://github.com/GenSpectrum/LAPIS-SILO/blob/13c1e0267a39da29084d4767508f3dd6e72a31da/endToEndTests/test/queries/booleanEquals_Or.json#L13
* The GET request almost shows that it works. Modifications confirm that it actually does work with GET.
* I also quickly checked locally.

**Comment by fengelniederhammer** [comment]
The SILO code is also quite explicit:
https://github.com/GenSpectrum/LAPIS-SILO/blob/13c1e0267a39da29084d4767508f3dd6e72a31da/src/silo/query_engine/filter_expressions/string_equals.cpp#L82-L85

**Comment by chaoran-chen** [comment]
Ah okay, that's super cool! Then, it certainly would be nice to fix the POST request and make it fully work. Priority-wise, after #754?

**Comment by JonasKellerer** [comment]
Just a reminder from #755: Null can not be entered on boolean columns in GET requests.
