### ISSUE TITLE
Is it intended that `,` in advanced queries behaves differently from `&`?

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/LAPIS#798]
Not thinking much, I used an advanced query `G2782T , T111C`.

Looking at the nucleotide mutations within things matched by that query, I noticed that T111C is only present in 20%.

So it seems that the notation `G2782T , T111C` means `maybe(G2782T) AND maybe(T111C)` whereas `G2782T & T111C` means `G2782T AND T111C`. Is that right? And is it intended?

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=G2782T+%26+T111C&

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=G2782T+%2C+T111C&

<img width="861" alt="Brave Browser 2024-05-16 12 39 06" src="https://github.com/GenSpectrum/cov-spectrum-website/assets/25161793/628fd4ab-edd4-4725-a4d1-55d95a43aba2">

<img width="869" alt="Brave Browser 2024-05-16 12 39 02" src="https://github.com/GenSpectrum/cov-spectrum-website/assets/25161793/b3ea94e6-e314-4ff8-843f-0be509e4fa12">

**Comment by fengelniederhammer** [comment]
Looks like a bug in LAPIS 2. When switching to "Open", which still runs on LAPIS 1, you get a "malformed variant query":
![grafik](https://github.com/GenSpectrum/cov-spectrum-website/assets/92720311/b1539457-5ff7-4de4-9b20-2cc0daa38ead)

**Comment by fengelniederhammer** [comment]
@chaoran-chen Should we actually allow or forbid sending multiple variant queries in a single request?

* Forbidding it would yield quite specific error messages
* Multiple values would be treated as "and" (as for any other sequence filter). Allowing it would implicitly make `,` on CoV Spectrum be interpreted as `&`, since comma separated values in query strings are decoded as arrays.

**Comment by fengelniederhammer** [comment]
As discussed: If the `variantQuery` is set, we expect exactly one value.

Providing multiple values for other filters mean "or", which would be weird for variant queries.
