### ISSUE TITLE
Healthcheck

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/LAPIS#813]
Related and complementary to #812, we should have a `HEALTHCHECK` in Docker to ensure that Docker detects when LAPIS is non-responsive. (Thanks to @theosanderson for suggesting this.)

**Comment by theosanderson** [comment]
Thanks - it would be great if this health endpoint returned status `200` while LAPIS is waiting for its first data, which other endpoints do not atm (as far as I am aware)

**Comment by chaoran-chen** [comment]
As soon as https://github.com/GenSpectrum/LAPIS-SILO/issues/244 is implemented, waiting for the first data shouldn't be a problem anymore, though.

**Comment by theosanderson** [comment]
Yes, great! I wasn't sure of the timing there. In the post-implementation-of-244 case, it may be possible to just use an existing endpoint for this.

**Comment by pflanze** [comment]
In case `curl` and Bash aren't working well enough for making the check program, I could extend my api-query program[1] for the purpose. I've verified that I can produce a statically linked binary.

[1] https://github.com/pflanze/api-query/blob/master/src/main.rs

**Comment by pflanze** [comment]
For sending slack messages at a later point, check with me as I already made a separately runnable script for that with extracts from the servers repo, and I'm already due to integrating that back ino a GenSpectrum repo in a way.

**Comment by fengelniederhammer** [comment]
Also see #941 for some more information.
