### ISSUE TITLE
Improve Docker tag name generation for branches

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/LAPIS#84]
The tags for the Docker images are derived from the branch names:

https://github.com/GenSpectrum/LAPIS/blob/56b7436680f0c01a6b52c917f3a8bc2bf547dc1f/.github/workflows/server_docker.yml#L22

This unfortunately often generates invalid tag names, especially for the branches created by the Dependabot:

![image](https://user-images.githubusercontent.com/18666552/213484265-541e3630-dec1-4945-af20-d86e7d658324.png)

**Comment by fengelniederhammer** [comment]
I think I already fixed that in #82 (https://github.com/GenSpectrum/LAPIS/pull/82/commits/c2b820451c70d46a1fc9aee1537ed88f33e3e887).
