### ISSUE TITLE
Allow setting of filename for downloaded file via URL param

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/LAPIS#869]
Right now it seems it's not possible to specify the file name that a downloaded file will have, i.e. I can't tell LAPIS to not use `details.json` as `filename` in content-disposition:

```
https://lapis.genspectrum.org/sample/details?limit=100&dataFormat=JSON&downloadAsFile=true
```

always responds with

<img width="597" alt="Hyper 2024-07-23 13 38 47" src="https://github.com/user-attachments/assets/424319c6-50ca-4063-ad92-68cfd156198d">

`details.json` is very generic and not great when used by downstream websites that use LAPIS.

It should be easy to add a `filename=` URL param that simply changes the header response. That is, whatever is passed by `filename` URL param should be used in the header field `Content-Disposition-> filename=`

Right now, filenames seem to be hardcoded per endpoint, see https://github.com/GenSpectrum/LAPIS/blob/972a16c525c1ba8b9cdde06e2626dcda58c34f87/lapis/src/test/kotlin/org/genspectrum/lapis/controller/LapisControllerDownloadAsFileTest.kt#L186-L197

Here, one should allow a file to be specified via URL param (otherwise keep using this by default): https://github.com/GenSpectrum/LAPIS/blob/972a16c525c1ba8b9cdde06e2626dcda58c34f87/lapis/src/main/kotlin/org/genspectrum/lapis/controller/middleware/DownloadAsFileFilter.kt#L39-L60

Might be as simple as changing the value here, and using URL param if set: https://github.com/GenSpectrum/LAPIS/blob/972a16c525c1ba8b9cdde06e2626dcda58c34f87/lapis/src/main/kotlin/org/genspectrum/lapis/controller/middleware/DownloadAsFileFilter.kt#L42-L43

**Comment by corneliusroemer** [comment]
It works, I've tested with real data - if someone could take over and finish off tests/docs that'd be great!

**Comment by corneliusroemer** [comment]
I didn't think much about what to call the URL param. `downloadFileBasename` is a bit of a mouthful, but it does convey the purpose. We could shorten it to `fileBasename` for example, but that would make the code less clear.

**Comment by fengelniederhammer** [comment]
Actually, we discussed that `downloadFileBasename` is a good name.
