### ISSUE TITLE
LAPIS outputs FASTA files reading `null` for missing segments

### ISSUE THREAD

**Issue by theosanderson** [GenSpectrum/LAPIS#912]
@rneher pointed out that when downloading unaligned segments that don't exist from LAPIS, one receives output formatted as:

```
>sequence1
null
```

from LAPIS.

This is not "valid" FASTA and would break many pipelines as `null` would be interpreted as a sequence

**Comment by corneliusroemer** [comment]
Just for future visitors to this issue:

IIUC, sequences that are null are now entirely omitted, so

```
>seqA
ACTG
>seqC
TTTT
```

as opposed to

```
>seqA
ACTG
>seqB

>seqC
TTTT
```

is that correct?

**Comment by fengelniederhammer** [comment]
> Just for future visitors to this issue:
> 
> IIUC, sequences that are null are now entirely omitted, so
> 
> ```
> >seqA
> ACTG
> >seqC
> TTTT
> ```
> 
> as opposed to
> 
> ```
> >seqA
> ACTG
> >seqB
> 
> >seqC
> TTTT
> ```
> 
> is that correct?

Yes :+1:
