### ISSUE TITLE
There should be general LAPIS docs, without database specific fields

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/LAPIS#928]
It appears every single LAPIS instance should set up its own docs instance? I think this is suboptimal: most content will be duplicated. It'd be nice if the invariant content was on a central LAPIS url, so that not every LAPIS user needs to have mostly identical content out there.

One can then just Google something and use the official docs (for invariant content)

Follow up from what I learned in https://github.com/GenSpectrum/LAPIS/issues/924

**Comment by fengelniederhammer** [comment]
I added links to the README in https://github.com/GenSpectrum/LAPIS/pull/998.

What remains to be done: Mark the parts in the docs that are dynamically generated for the specific config.
