### ISSUE TITLE
S:4865P causes crash

### ISSUE THREAD

**Issue by jasondorjeshort** [GenSpectrum/LAPIS#95]
The site has numerous bugs - often it can get into a repeating loop where it reloads the same page indefinitely, other times it can just freeze up.

But this is the first time I got this message so here I am.

This is loading "nextcladePangoLineage:xbb* & S:4865p" but not-advanced-search from India region.

![bug](https://user-images.githubusercontent.com/17172327/214757373-cd165356-a4af-44fb-b0f4-8ee1f8691bc0.png)

**Comment by jasondorjeshort** [comment]
Ah hah.  It's S:4865p causing a crash.

**Comment by chaoran-chen** [comment]
Thanks for creating this issue! Yes, the S-gene does not have 4865 bases :)

This is a good example that we need better error messages (#3)!
