### ISSUE TITLE
make it possible to return sequences as JSON or NDJSON

### ISSUE THREAD

**Issue by fengelniederhammer** [GenSpectrum/LAPIS#971]
Currently, the sequences endpoints only return FASTA, which is nice for downloading files. But when working with LAPIS programmatically, a structured response would be better.

Implement getting the sequences as JSON or NDJSON (or both, if easily possible). The default should still be FASTA.

Make sure that the result can still be streamed properly. 
* This should be straight forward for NDJSON.
* Think about how to stream JSON. (Maybe just write `[`, then NDJSON lines separated by `,` and then `]`?)

**Comment by corneliusroemer** [comment]
It seems the default is now no longer FASTA? See https://github.com/loculus-project/loculus/pull/3077#issuecomment-2438356390

**Comment by fengelniederhammer** [comment]
> It seems the default is now no longer FASTA? See [loculus-project/loculus#3077 (comment)](https://github.com/loculus-project/loculus/pull/3077#issuecomment-2438356390)

AFAICS the issue has been resolved in Loculus?
