### ISSUE TITLE
Reject regex separator in metadata fields

### ISSUE THREAD

**Issue by fengelniederhammer** [GenSpectrum/LAPIS#976]
Validate that metadata fields don't contain the regex separator (`-` or `$`, depending on decision). LAPIS will use `metadataField-regex` or `metadataField$regex` for the regex search and thus the separator should not be contained in the metadata field name.

**Comment by corneliusroemer** [comment]
It's confusing that the issue mentions $ and - but the change log entry references `.` 

IIUc, the latter is correct and the former outdated, right? Maybe update the issue to that effect.

**Comment by fengelniederhammer** [comment]
Yes, we later changed the separator from `$` to `.`.
