### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by fhennig** [GenSpectrum/LAPIS#991]
Hi, I couldn't find documentation for the LAPIS API in the README. Where is it?

**Comment by corneliusroemer** [comment]
You can find general docs here: https://lapis-three.vercel.app/

**Comment by corneliusroemer** [comment]
Also, see #928

**Comment by Taepper** [comment]
Ah, indeed https://github.com/GenSpectrum/LAPIS/issues/928 seems to be more descriptive and a duplicate of this. I will therefore close this as a duplicate. It is still on the agenda for Wednesday and we will prioritize it accordingly
